apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-rhtap-mc-unsuported-runtime-0aqd
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-npap-tenant/mc-unsupported-runtime/devfile-sample-python-basic-rhtap-mc-unsuported-runtime-0aqd@sha256:7d1ba4a0ba126d1d1c0aa557a7e9fc7f0894eadb7056ba4c89a6495aad4dfbce
        name: my-python
        resources: {}
status: {}
